version: '3'

networks:
  default:
    driver: bridge

services:
  redis:
    container_name: redis
    hostname: redis
    image: redis
    ports:
    - "6379:6379"
    networks:
    - default
  visual-voyager:
    container_name: visual-voyager
    build: 
      context: ./visual-voyager/
    ports:
    - "3002:3002"
    environment:
    - PORT=3002  
    networks:
    - default
  data-demon:
    container_name: data-demon
    build: 
      context: ./data-demon/
    ports:
    - "3001:3001"
    links:
    - redis
    - visual-voyager
    environment:
    - PORT=3001
    networks:
      - default